### ISSUE TITLE
Output scrollbar display on linux

### ISSUE THREAD

**Issue by strob** [Glench/Flowsheets-v2#7]
On certain 19th and 20th century operating systems, the default scrollbar display obscures the output and blocks resizing operations:
![screenshot from 2017-08-09 09-17-38](https://user-images.githubusercontent.com/208551/29110006-74fbe23e-7ce5-11e7-9246-e8d0ee8ec304.png)

While it seems like some thought went into this[0], for me what seems to work (based on [the modern internet](https://coderwall.com/p/h_zpfa/hide-scrollbars-in-atom)) is a sub-element selector in ```.output``` that disables the display of the scrollbar entirely:

```css
& > *::-webkit-scrollbar {
    display: none;
}
```
Opening an issue instead of a pull request for now because I'm not sure I understand all of the implications of this change.

[0] https://github.com/Glench/Flowsheets-v2/blob/4a0da6e66d321b221b2e08c47100ee3341341a02/src/style.less#L142-L146

**Comment by Glench** [comment]
Ideally I'd like the vertical scrollbar to show up on scrollable entries, but who knows how to do that these days.

**Comment by Glench** [comment]
Does changing this line:

```
    .output {
        overflow: hidden;

        & > * {
            height: 100%;
            overflow: scroll;
        }
```
from `overflow: scroll;` to `overflow: auto;` change anything without the webkit change?

**Comment by Glench** [comment]
Nevermind, I installed a linux virtual machine and tested it. Should be okay now.
